version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newdb
    ports:
      - "5434:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

  app:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/newdb
      USE_REDIS: "true"  # Default set to "false" (will use DB)
    ports:
      - "1114:8000"
    networks:
      - my_network
    volumes:
      - .:/app

networks:
  my_network:

volumes:
  postgres_data: